# Generated by Django 5.2.6 on 2025-09-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.RunSQL(
            """
            PRAGMA table_info(main_product);
            CREATE TABLE main_product_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                name TEXT NOT NULL,
                price INTEGER NOT NULL DEFAULT 0,
                description TEXT NOT NULL,
                category VARCHAR(20) NOT NULL DEFAULT 'update',
                thumbnail TEXT,
                is_featured BOOLEAN NOT NULL DEFAULT 0,
                FOREIGN KEY (user_id) REFERENCES auth_user(id)
            );
            INSERT INTO main_product_new (id, user_id, name, price, description, category, thumbnail, is_featured)
            SELECT id, user_id, name, price, description, category, thumbnail, is_featured FROM main_product;
            DROP TABLE main_product;
            ALTER TABLE main_product_new RENAME TO main_product;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
