# Generated by Django 5.2.6 on 2025-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20251001_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('celana', 'Celana'), ('joggers', 'Joggers'), ('kaus kaki', 'Kaus Kaki'), ('bola', 'Bola'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
